queue_rules:
  - name: default
    conditions:
      - check-success=Test stable
      - check-success=Test beta
      - check-success=Test nightly
      - check-success=Test 1.45.0

pull_request_rules:
  - name: Queue on approval with success checks
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=Test stable
      - check-success=Test beta
      - check-success=Test nightly
      - check-success=Test 1.45.0
    actions:
      queue:
        name: default

  - name: Queue on success checks for sbosnick
    conditions:
      - author=sbosnick
      - check-success=Test stable
      - check-success=Test beta
      - check-success=Test nightly
      - check-success=Test 1.45.0
    actions:
      queue:
        name: default
