[package]
name = "semantic-release-rust"
version ="1.0.0-alpha.7"
authors = ["Steven Bosnick <sbosnick@sympatico.ca>"]
edition = "2018"
description = "A CLI to integrate Rust into a semantic-release workflow."
readme = "README.md"
repository = "https://github.com/sbosnick/semantic-release-rust"
license = "MIT OR Apache-2.0"
keywords = ["release", "semantic-release", "command-line-tool"]
categories = ["command-line-utilities", "development-tools::build-utils"]

[dependencies]
human-panic = "1.0.3"
log = "0.4.14"
loggerv = "0.7.2"
structopt = "0.3.21"
anyhow = "1.0.38"
thiserror = "1.0.23"
guppy = "0.7.0"
itertools = "0.10.0"
toml_edit = "0.2.0"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"
url = { version = "2.2.0", features = ["serde"] }

[dev-dependencies]
assert_matches = "1.5.0"
tempfile = "3.2.0"
fs_extra = "1.2.0"
semver = "0.11.0"
