[package]
name = "semantic-release-rust"
version ="1.0.0-alpha.4"
authors = ["Steven Bosnick <sbosnick@sympatico.ca>"]
edition = "2018"
description = "A CLI to integrate Rust into a semantic-release workflow."
readme = "README.md"
repository = "https://github.com/sbosnick/semantic-release-rust"
license = "MIT OR Apache-2.0"
keywords = ["release", "semantic-release", "command-line-tool"]
categories = ["command-line-utilities", "development-tools::build-utils"]

[dependencies]
human-panic = "1.0.3"
log = "0.4.8"
loggerv = "0.7.2"
structopt = "0.3.15"
anyhow = "1.0.31"
thiserror = "1.0.20"
guppy = "0.5.0"
itertools = "0.9.0"
toml_edit = "0.2.0"
serde = {version = "1.0.114", features = ["derive"]}
serde_json = "1.0.57"
url = {version = "2.1.1", features = ["serde"]}

[dev-dependencies]
assert_matches = "1.3.0"
tempfile = "3.1.0"
fs_extra = "1.1.0"
semver = "0.9.0"
