name: Automerge

on:
    pull_request:
        types:
            - labeled
            - unlabeled
            - synchronize
            - opened
            - edited
            - ready_for_review
            - reopended
            - unlocked
    pull_request_review:
        types:
            - submitted
    check_suite:
        types:
            - completed
    status: {}

jobs:
    auto_merge:
        name: Auto Approve PR
        runs-on: ubuntu-latest
        if: github.actor == 'sbosnick-bot'
        steps:
           - name: Auto Merge
             uses: pascalgn/automerge-action@v0.9.0
             env:
                 GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                 MERGE_METHOD: "squash"
                 MERGE_COMMIT_MESSAGE: "pull-request-title-and-description"
                 MERGE_FORKS: "false"
                 MERGE_RETRIES: "10"
                 MERGE_RETRY_SLEEP: "10000"
